/**
 * Codex Agent
 *
 * Wraps OpenAI's Codex CLI in non-interactive `codex exec --json` mode.
 * The orchestrator is responsible for creating a scoped CODEX_HOME and
 * allowlisted environment before this class is constructed.
 */

import { execSync, ChildProcess } from "child_process";
import * as fs from "fs";
import * as path from "path";
import type { AgentRunOptions, CodexConfiguration } from "../types.js";
import type { TelemetrySession } from "../telemetry/index.js";
import type { LogEventType } from "../telemetry/types.js";
import { readMcpServersFromPath } from "../mcp/index.js";
import type { McpServerSpec, McpServersFile } from "../mcp/index.js";
import {
  agentReasoningEvent,
  agentTextEvent,
  shellResultEvent,
  structuredResultEvent,
  toolCallEvent,
} from "./events.js";
import { runStreamingCli } from "./streaming-cli.js";

type JsonRecord = Record<string, unknown>;

function resolveCodexBinary(): string {
  try {
    const result = execSync("which codex", {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    if (result) return result;
  } catch {
    // Fall through to known paths.
  }

  const knownPaths = [
    "/root/.local/bin/codex",
    "/usr/local/bin/codex",
  ];
  for (const p of knownPaths) {
    if (fs.existsSync(p)) {
      return p;
    }
  }

  throw new Error(
    "Codex CLI not found. Checked: `which codex`, /root/.local/bin/codex, /usr/local/bin/codex.\n" +
    "Install with: curl -fsSL https://chatgpt.com/codex/install.sh | sh"
  );
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function isJsonRecord(value: unknown): value is JsonRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function toCodexMcpToml(file: McpServersFile): string {
  const lines: string[] = [];
  for (const [name, spec] of Object.entries(file.servers)) {
    lines.push(`[mcp_servers.${tomlString(name)}]`);
    lines.push("enabled = true");
    const entry = codexServerEntry(spec);
    for (const line of entry.main) {
      lines.push(line);
    }
    if (entry.env.length > 0) {
      lines.push(`[mcp_servers.${tomlString(name)}.env]`);
      for (const line of entry.env) {
        lines.push(line);
      }
    }
    lines.push("");
  }
  return lines.join("\n");
}

function codexServerEntry(spec: McpServerSpec): { main: string[]; env: string[] } {
  if (spec.transport === "http") {
    return {
      main: [`url = ${tomlString(spec.url)}`],
      env: [],
    };
  }

  const [command, ...args] = spec.command;
  const main = [`command = ${tomlString(command)}`];
  if (args.length > 0) {
    main.push(`args = [${args.map(tomlString).join(", ")}]`);
  }
  const env = Object.entries(spec.env ?? {}).map(
    ([key, value]) => `${tomlString(key)} = ${tomlString(value)}`
  );
  return { main, env };
}

export class CodexAgent {
  private config: CodexConfiguration;
  private session: TelemetrySession | null = null;
  private cliProcess: ChildProcess | null = null;
  private codexBinary: string;

  constructor(config: CodexConfiguration) {
    this.config = config;
    this.codexBinary = resolveCodexBinary();
    this.log("info", `CodexAgent initialized (model: ${config.model}, binary: ${this.codexBinary})`);
  }

  setTelemetrySession(session: TelemetrySession): void {
    this.session = session;
  }

  private log(
    type: LogEventType,
    message: string,
    data?: Record<string, unknown>
  ): void {
    if (this.session) {
      this.session.log(type, message, data);
    } else {
      console.log(message);
    }
  }

  private logError(message: string, data?: Record<string, unknown>): void {
    if (this.session) {
      this.session.log("error", message, data);
    } else {
      console.error(message);
    }
  }

  private emit(event: ReturnType<typeof toolCallEvent>): void {
    this.log(event.type, event.message, event.data);
  }

  private setupCodexConfig(): string | undefined {
    const codexHome = this.resolveCodexHome();
    fs.mkdirSync(codexHome, { recursive: true });
    const configPath = path.join(codexHome, "config.toml");

    const lines: string[] = [
      "# Generated by Hyperfocal for this Codex rollout.",
      "# Do not edit; the orchestrator recreates this file per run.",
      "",
      "[shell_environment_policy]",
      'inherit = "all"',
      "",
    ];

    const neutralPath = this.config.mcpConfigPath;
    if (neutralPath) {
      const file = readMcpServersFromPath(neutralPath);
      if (!file && fs.existsSync(neutralPath)) {
        this.logError(
          `Failed to parse neutral mcp-servers file at ${neutralPath} — running without MCP`
        );
      }
      if (file && Object.keys(file.servers).length > 0) {
        lines.push(toCodexMcpToml(file));
        this.log("info", `MCP active: ${Object.keys(file.servers).join(", ")}`, {
          servers: Object.keys(file.servers),
          source: neutralPath,
        });
      }
    }

    fs.writeFileSync(configPath, lines.join("\n"), { mode: 0o600 });
    this.log("info", `Wrote Codex config: ${configPath}`, { configPath });
    return configPath;
  }

  private resolveCodexHome(): string {
    if (process.env.CODEX_HOME) {
      return process.env.CODEX_HOME;
    }

    const homeDir = process.env.HOME || "/root";
    const runtimeDir = path.join(
      homeDir,
      ".local/share/codex/runtime/hyperfocal-child",
      `${Date.now()}-${process.pid}`
    );
    fs.mkdirSync(runtimeDir, { recursive: true });

    const sourceAuth = path.join(homeDir, ".codex", "auth.json");
    const targetAuth = path.join(runtimeDir, "auth.json");
    if (fs.existsSync(sourceAuth)) {
      fs.copyFileSync(sourceAuth, targetAuth);
      fs.chmodSync(targetAuth, 0o600);
      this.log("info", `Copied Codex auth.json into fallback CODEX_HOME: ${runtimeDir}`);
    }

    process.env.CODEX_HOME = runtimeDir;
    return runtimeDir;
  }

  private buildCLIArgs(prompt: string, workingDir: string, schemaPath?: string): string[] {
    const sandbox = this.config.sandbox || "danger-full-access";
    const approvalPolicy = this.config.approvalPolicy || "never";
    const args = [
      "--ask-for-approval", approvalPolicy,
      "exec",
      "--json",
      "--sandbox", sandbox,
      "--skip-git-repo-check",
      "--cd", workingDir,
      "--model", this.config.model,
      "-c", "model_reasoning_summary=detailed",
      "-c", "show_raw_agent_reasoning=true",
    ];
    if (schemaPath) {
      args.push("--output-schema", schemaPath);
    }
    args.push(prompt);
    return args;
  }

  async run(
    prompt: string,
    workingDir: string,
    options?: AgentRunOptions
  ): Promise<void> {
    if (!prompt?.trim()) {
      throw new Error("Prompt must be a non-empty string");
    }

    const sandbox = this.config.sandbox || "danger-full-access";
    const approvalPolicy = this.config.approvalPolicy || "never";
    this.log("info", `Using Codex CLI (${this.config.model}, sandbox: ${sandbox})`);
    // Codex runs the explicit --model string verbatim, so resolved == requested.
    this.session?.setResolvedModel(this.config.model);
    this.log(
      "info",
      `Prompt: ${prompt.substring(0, 100)}${prompt.length > 100 ? "..." : ""}`,
      { promptLength: prompt.length }
    );
    this.log("info", `Working directory: ${workingDir}`);

    this.setupCodexConfig();
    const cliArgs = this.buildCLIArgs(prompt, workingDir, options?.schemaPath);

    this.log("info", "Starting Codex CLI", {
      args: cliArgs,
      binary: this.codexBinary,
      sandbox,
      approvalPolicy,
    });

    let result: Awaited<ReturnType<typeof runStreamingCli>>;
    try {
      result = await runStreamingCli({
        command: this.codexBinary,
        args: cliArgs,
        cwd: workingDir,
        stdin: "ignore",
        env: {
          ...process.env,
          HOME: process.env.HOME || "/root",
        },
        debugLogStream: this.createDebugLogStream(),
        onProcess: (child) => {
          this.cliProcess = child;
        },
        onStdoutLine: (line) => {
          if (!line.trim()) return;
          try {
            const event = JSON.parse(line) as JsonRecord;
            this.handleEvent(event);
          } catch {
            this.log("info", line);
          }
        },
        onStderrText: (text) => {
          if (text.includes("Error") || text.includes("error") || text.includes("Not logged in")) {
            this.logError(`CLI stderr: ${text.trim()}`);
          }
        },
      });
    } catch (error) {
      const message = `Failed to start Codex CLI: ${error instanceof Error ? error.message : String(error)}`;
      this.logError(`Error: ${message}`);
      throw new Error(message);
    }

    if (result.code !== 0 || result.signal) {
      let errorMessage = result.signal
        ? `Codex CLI terminated with signal ${result.signal}`
        : `Codex CLI exited with code ${result.code}`;
      if (result.stderrChunks.length > 0) {
        errorMessage += `\nStderr: ${result.stderrChunks.join("").slice(-1000)}`;
      }
      this.logError(`Error: ${errorMessage}`);
      throw new Error(errorMessage);
    }

    this.log("info", "Codex CLI completed", {
      exitCode: result.code,
      completionSource: result.completionSource,
    });
  }

  private createDebugLogStream(): fs.WriteStream | undefined {
    if (!this.config.codingAgentDebugLogs || !this.session) return undefined;
    return fs.createWriteStream(this.session.getDebugLogPath(), { flags: "a" });
  }

  private handleEvent(event: JsonRecord): void {
    const type = typeof event.type === "string" ? event.type : "unknown";

    if (type === "item.started" || type === "item.updated" || type === "item.completed") {
      this.handleItemEvent(type, event);
      return;
    }

    if (type === "turn.completed") {
      this.log("info", "Turn completed", event);
      return;
    }

    if (type === "thread.started") {
      this.log("info", "Codex thread started", event);
      return;
    }

    if (type === "error") {
      this.logError(`Codex error: ${JSON.stringify(event).slice(0, 500)}`, event);
      return;
    }

    this.log("info", `Codex event: ${type}`, event);
  }

  private handleItemEvent(type: string, event: JsonRecord): void {
    const item = isJsonRecord(event.item) ? event.item : event;
    const itemType = typeof item.type === "string" ? item.type : "unknown";

    if (itemType === "agent_message") {
      const text = typeof item.text === "string" ? item.text : JSON.stringify(item);
      this.emit(agentTextEvent(text));
      return;
    }

    if (itemType === "reasoning") {
      const text = typeof item.text === "string" ? item.text : JSON.stringify(item);
      this.emit(agentReasoningEvent(text));
      return;
    }

    if (itemType === "command_execution") {
      const toolUseId = this.getItemId(item);
      const command = this.getCommand(item);
      if (type === "item.started") {
        this.emit(toolCallEvent({
          tool: "command_execution",
          toolUseId,
          family: "shell",
          input: {
            command,
            status: this.getStatus(item),
          },
          message: `command_execution: ${command}`,
        }));
      } else {
        this.emit(shellResultEvent({
          tool: "command_execution",
          toolUseId,
          stdout: this.getAggregatedOutput(item),
          stderr: "",
          exitCode: this.getExitCode(item),
          status: this.getStatus(item),
          message: `command_execution completed: ${command}`,
        }));
      }
      return;
    }

    if (itemType === "file_change") {
      this.emit(toolCallEvent({
        tool: "file_change",
        toolUseId: this.getItemId(item),
        family: "file",
        input: {
          changes: Array.isArray(item.changes) ? item.changes : [],
          status: this.getStatus(item),
        },
        message: `file_change: ${JSON.stringify(item.changes ?? []).slice(0, 200)}`,
      }));
      return;
    }

    if (itemType === "todo_list") {
      this.emit(toolCallEvent({
        tool: "todo_list",
        toolUseId: this.getItemId(item),
        family: "todo",
        input: {
          items: Array.isArray(item.items) ? item.items : [],
        },
        message: `todo_list: ${JSON.stringify(item.items ?? []).slice(0, 200)}`,
      }));
      return;
    }

    if (itemType === "mcp_tool_call") {
      const server = typeof item.server === "string" ? item.server : "mcp";
      const tool = typeof item.tool === "string" ? item.tool : "tool";
      const toolName = `mcp:${server}.${tool}`;
      const toolUseId = this.getItemId(item);
      if (type === "item.started") {
        this.emit(toolCallEvent({
          tool: toolName,
          toolUseId,
          family: "mcp",
          input: {
            server,
            tool,
            arguments: item.arguments,
            status: this.getStatus(item),
          },
          message: `${toolName}: ${JSON.stringify(item.arguments ?? {}).slice(0, 200)}`,
        }));
      } else {
        this.log("tool_result", `${toolName} completed`, {
          tool: toolName,
          tool_use_id: toolUseId,
          tool_family: "mcp",
          result: item.result ?? null,
          error: item.error ?? null,
          status: this.getStatus(item),
          is_error: item.error != null,
        });
      }
      return;
    }

    if (itemType === "tool_call" || itemType === "function_call") {
      this.emit(toolCallEvent({
        tool: itemType,
        toolUseId: this.getItemId(item),
        family: "generic",
        input: item,
        message: `${itemType}: ${JSON.stringify(item).slice(0, 200)}`,
      }));
      return;
    }

    if (itemType === "tool_result" || itemType === "function_call_output") {
      this.emit(structuredResultEvent({
        tool: itemType,
        toolUseId: this.getItemId(item),
        result: item,
        message: `${itemType}: ${JSON.stringify(item).slice(0, 200)}`,
      }));
      return;
    }

    // Codex item payloads are normalized into the fields above so the trace
    // viewer has a stable contract. Provider-only details that do not map
    // cleanly (new item fields, partial command output updates, or future
    // protocol variants) are not copied into product JSONL; enable coding
    // agent debug logs to inspect the raw CLI stream when those details matter.
    this.log("info", `Codex item ${type}: ${itemType}`, event);
  }

  private getItemId(item: JsonRecord): string | undefined {
    return typeof item.id === "string" ? item.id : undefined;
  }

  private getStatus(item: JsonRecord): string | undefined {
    return typeof item.status === "string" ? item.status : undefined;
  }

  private getCommand(item: JsonRecord): string {
    return typeof item.command === "string"
      ? item.command
      : JSON.stringify(item.command);
  }

  private getAggregatedOutput(item: JsonRecord): string {
    return typeof item.aggregated_output === "string"
      ? item.aggregated_output
      : "";
  }

  private getExitCode(item: JsonRecord): number | null | undefined {
    return typeof item.exit_code === "number" || item.exit_code === null
      ? item.exit_code
      : undefined;
  }

  getModel(): string {
    return this.config.model;
  }

  getConfiguration(): CodexConfiguration {
    return { ...this.config };
  }
}
