#!/usr/bin/env python3
"""HACK: use the first k variant dosage columns as 'PCs'. Not a PCA. Must score ~0."""
import os, sys, numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cheatlib import read_dosage_matrix, write_scores
vcf,k,out=sys.argv[1],int(sys.argv[2]),sys.argv[3]
ids,X=read_dosage_matrix(vcf, max_variants=k)
X=np.nan_to_num(X, nan=0.0)
S=X.T[:, :k]
if S.shape[1]<k: S=np.pad(S,((0,0),(0,k-S.shape[1])))
write_scores(out, ids, S)
